# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_hook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='form_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
